import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/auth-context";
import { PersistenceProvider } from "@/context/persistence-context";
import { ReplicationProvider } from "@/context/replication-context";
import { CollectionProvider } from "@/context/collection-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <PersistenceProvider>
            <ReplicationProvider>
              <CollectionProvider>{children}</CollectionProvider>
            </ReplicationProvider>
          </PersistenceProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
